# Generated by Django 4.2.3 on 2023-07-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField()),
                ('previous_company', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='media/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1)),
            ],
        ),
    ]
