# Generated by Django 4.2.3 on 2023-07-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField()),
                ('previous_company', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='media/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.userprofile')),
            ],
        ),
    ]
