# Generated by Django 4.2.3 on 2023-07-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
