# Generated by Django 4.2.3 on 2023-08-01 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0003_delete_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=200)),
                ('completion_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='previous_company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CertificationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certification_files/')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.certification')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certification_files',
            field=models.ManyToManyField(blank=True, to='homepage.certificationfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certifications',
            field=models.ManyToManyField(blank=True, to='homepage.certification'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='highest_education',
            field=models.ManyToManyField(blank=True, to='homepage.education'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_applying_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.job'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='previously_employed_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.previousjob'),
        ),
    ]
