# Generated by Django 4.2.3 on 2023-08-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='certification_files',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='highest_education',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='job_applying_for',
        ),
    ]
