# Generated by Django 4.2.3 on 2023-08-07 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_remove_userprofile_certification_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='certification_files',
            field=models.ManyToManyField(related_name='user_profiles', to='homepage.certificationfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certifications',
            field=models.ManyToManyField(related_name='user_profiles', to='homepage.certification'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='highest_education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='homepage.education'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_applying_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='homepage.job'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='previously_employed_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='former_employees', to='homepage.previousjob'),
        ),
    ]
