# Generated by Django 4.2.3 on 2023-08-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_remove_certificationfile_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
