# Generated by Django 4.2.3 on 2023-08-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
