# Generated by Django 4.2.3 on 2023-08-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_userprofile_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_appfor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
