# Generated by Django 4.2.3 on 2023-08-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_userprofile_job_appfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='previous_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
